name: YOURNAME_fasterrcnn_coco_pytorch_const
data:
  url: https://determined-ai-public-datasets.s3-us-west-2.amazonaws.com/PennFudanPed/PennFudanPed.zip
hyperparameters:
  learning_rate: 0.005
  momentum: 0.9
  weight_decay: 0.0005
  global_batch_size: 2
searcher:
  name: single
  metric: val_avg_iou
  smaller_is_better: false
  max_length:
    batches: 400
min_validation_period:
  batches: 100
scheduling_unit: 50
profiling:
  enabled: true
  begin_on_batch: 0
  end_after_batch: null
entrypoint: model_def:ObjectDetectionTrial

