name: dogcat_distributed
data:
#    dir: /scratch/mlde/dataset/dogs-and-cats/train
    dir: /run/determined/workdir/shared_fs/train
labels:
  - "4 GPU"
hyperparameters:
    learning_rate: .005
    global_batch_size: 16
    weight_decay: 1e-4
    nesterov: True
min_validation_period:
    batches: 400
searcher:
    name: single
    metric: accuracy
    max_length:
        batches: 1024
    smaller_is_better: false
entrypoint: model_def:DogCatModel
resources:
    slots_per_trial: 4
max_restarts: 0
profiling:
    enabled: true
    begin_on_batch: 0
    end_after_batch: null
